dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'io.asyncer:r2dbc-mysql'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
}

